inherit_gem:
  bixby: bixby_default.yml

AllCops:
    TargetRubyVersion: 2.5
    Exclude:
        - 'bin/**/*'
        - 'db/**/*'
        - 'tmp/**/*'
        - 'vendor/**/*'
        - 'node_modules/**/*'

Metrics/ClassLength:
    Exclude:
        - 'app/models/marc_indexer.rb'

Metrics/AbcSize:
    Exclude:
        - 'app/models/marc_indexer.rb'
        - 'app/services/oai_processing_service.rb'
        - 'lib/tasks/sample_scheduler.rake'

Metrics/BlockLength:
    Exclude:
        - app/controllers/catalog_controller.rb
        - config/routes.rb
        - spec/controllers/catalog_controller_spec.rb
        - spec/models/marc_indexing_spec.rb
        - spec/models/property_bag_spec.rb
        - spec/models/user_spec.rb
        - spec/services/oai_processing_service_spec.rb
        - spec/spec_helper.rb
        - spec/system/facet_by_year_spec.rb
        - spec/system/targeted_field_search_spec.rb
        - spec/system/view_search_results_spec.rb
        - spec/system/view_show_page_spec.rb

Metrics/CyclomaticComplexity:
    Exclude:
        - 'app/models/marc_indexer.rb'

Metrics/MethodLength:
    Exclude:
        - 'app/models/marc_indexer.rb'
        - 'app/services/oai_processing_service.rb'
        - 'lib/tasks/sample_scheduler.rake'

Metrics/PerceivedComplexity:
    Exclude:
        - 'app/models/marc_indexer.rb'

Lint/EmptyWhen:
    Exclude:
        - app/models/marc_indexer.rb

Lint/PercentStringArray:
    Exclude:
        - 'config/initializers/secure_headers.rb'

Rails/Output:
    Exclude:
        - 'app/services/oai_processing_service.rb'

RSpec/DescribeClass:
    Exclude:
        - 'spec/models/marc_indexing_spec.rb'

RSpec/ExampleLength:
    Exclude:
        - spec/requests/not_found_requests_spec.rb
        - spec/routing/alma_availability_routes_spec.rb
        - spec/services/oai_processing_service_spec.rb
        - spec/system/facet_by_year_spec.rb
        - spec/system/targeted_field_search_spec.rb
        - spec/system/view_show_page_spec.rb