inherit_gem:
  bixby: bixby_default.yml

AllCops:
    TargetRubyVersion: 3.2
    Exclude:
        - 'bin/**/*'
        - 'db/**/*'
        - 'tmp/**/*'
        - 'vendor/**/*'
        - 'node_modules/**/*'
        - 'app/models/concerns/document_delivery_requestable.rb'
        - 'app/models/concerns/special_collections_requestable.rb'
        - 'app/models/concerns/blacklight/marc/document_export.rb'
        - 'app/models/concerns/statusable.rb'
        - 'lib/solr/*'

Layout/LineLength:
    Exclude:
        - 'spec/support/solr_documents/*'

Metrics/AbcSize:
    Exclude:
        - 'app/models/concerns/blacklight/solr/document/marc_export.rb'
        - 'app/services/oai_processing_service.rb'
        - 'app/services/oai_processing_single_service.rb'
        - 'lib/chicago_citation_formatter.rb'
        - 'lib/traject/extract_subject.rb'
        - 'app/helpers/citation_modal_helper.rb'

Metrics/BlockLength:
    Exclude:
        - 'app/controllers/catalog_controller.rb'
        - 'config/initializers/simple_form_bootstrap.rb'
        - 'config/routes.rb'
        - 'lib/tasks/marc_index_ingester.rake'
        - 'config/initializers/catalog_index_override.rb'
        - 'spec/**/*'

Metrics/ClassLength:
    Exclude:
        - 'app/models/hold_request.rb'
        - 'app/controllers/catalog_controller.rb'

Metrics/CyclomaticComplexity:
    Exclude:
        - 'app/models/concerns/blacklight/solr/document/marc_export.rb'
        - 'app/models/marc_indexer.rb'
        - 'app/services/oai_processing_single_service.rb'
        - 'lib/traject/extract_publication_date.rb'
        - 'lib/traject/extract_url_fulltext.rb'
        - 'lib/traject/extract_url_suppl.rb'

Metrics/MethodLength:
    Exclude:
        - 'app/models/concerns/blacklight/solr/document/marc_export.rb'
        - 'app/services/oai_processing_service.rb'
        - 'app/services/oai_processing_single_service.rb'
        - 'app/helpers/citation_modal_helper.rb'
        - 'lib/traject/extract_publication_date.rb'
        - 'lib/traject/extract_url_fulltext.rb'
        - 'lib/traject/extract_subject_display.rb'
        - 'lib/traject/extract_subject.rb'
        - 'lib/chicago_citation_formatter.rb'
        - 'app/controllers/sessions/social_login.rb'
        - 'config/initializers/bookmarks_index_override.rb'
        - 'config/initializers/catalog_index_override.rb'

Metrics/ModuleLength:
    Exclude:
        - 'app/models/concerns/blacklight/solr/document/marc_export.rb'
        - 'lib/traject/extraction_tools.rb'
        - 'lib/traject/extract_subject.rb'
        - 'config/prepends/custom_citation_logic.rb'
        - 'app/models/concerns/statusable.rb'
        - 'app/helpers/catalog_helper.rb'
        - 'app/services/oai_processing/oai_processing_toolset.rb'

Metrics/PerceivedComplexity:
    Exclude:
        - 'app/models/concerns/blacklight/solr/document/marc_export.rb'
        - 'app/models/marc_indexer.rb'
        - 'lib/traject/extract_publication_date.rb'

Lint/EmptyWhen:
    Exclude:
        - 'app/models/marc_indexer.rb'

Lint/PercentStringArray:
    Exclude:
        - 'config/initializers/secure_headers.rb'

Rails/Exit:
    Exclude:
        - 'config/deploy.rb'

Rails/Output:
    Exclude:
        - 'config/deploy.rb'

Rails/OutputSafety:
    Exclude:
        - 'app/helpers/citation_modal_helper.rb'
        - 'app/models/concerns/blacklight/solr/document/marc_export.rb'

RSpec/DescribeClass:
    Exclude:
        - 'spec/models/marc_indexing_spec.rb'

RSpec/ExampleLength:
    Exclude:
        - 'spec/**/*'

RSpec/MessageSpies:
    EnforcedStyle: 'receive'

Style/Next:
    Exclude:
        - 'app/models/concerns/blacklight/solr/document/marc_export.rb'
