version: '3'

services:
  app:
    build: .
    depends_on:
      - mysql-dev
      - mysql-test
      - solr-dev
      - solr-test
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/app/bundle
  
  mysql-dev:
    platform: linux/x86_64
    image: mysql:8.0-debian
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: # set root password here
      MYSQL_USER: emory-ltds
      MYSQL_PASSWORD: # set same password as DATABASE_PASSWORD in .env.development
      MYSQL_DATABASE: blacklight-catalog-dev
    volumes:
      - mysql-dev:/var/lib/mysql
  
  mysql-test:
    platform: linux/x86_64
    image: mysql:8.0-debian
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: # set root password here
      MYSQL_USER: emory-ltds
      MYSQL_PASSWORD: # set same password as DATABASE_PASSWORD in .env.test
      MYSQL_DATABASE: blacklight-catalog-test
    volumes:
      - mysql-test:/var/lib/mysql

  solr-dev:
    platform: linux/x86_64
    image: solr:8.11.2-slim
    volumes:
      - $PWD/solr/conf:/opt/solr/conf
      - solr-dev:/var/solr
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - blacklight-core
      - /opt/solr/conf
  
  solr-test:
    platform: linux/x86_64
    image: solr:8.11.2-slim
    volumes:
      - $PWD/solr/conf:/opt/solr/conf
      - solr-test:/var/solr
    ports:
      - "8985:8983"
    command:
      - solr-precreate
      - blacklight-test
      - /opt/solr/conf
volumes:
  bundle:
  mysql-dev:
  mysql-test:
  solr-dev:
  solr-test:
