title_addl_tesim: 'Full Title'
title_uniform_ssim: 'Uniform Title'
title_former_ssim: 'Former Titles'
title_later_ssim: 'Later Titles'
title_series_ssim: 'Series Titles'
emory_collection_tesim: 'Collection'
