title_addl_tesim: 'Full Title'
title_uniform_ssim: 'Uniform Title'
title_former_ssim: 'Former Titles'
title_later_ssim: 'Later Titles'
title_series_ssim: 'Series Titles'
emory_collection_tesim: 'Collection'
title_added_entry_tesim: 'Related/Included Titles'
title_varying_tesim: 'Variant Titles'
title_abbr_tesim: 'Abbreviated Titles'
title_translation_tesim: 'Translated Titles'