title_details_display_tesim: 'Title'
title_addl_tesim: 'More Title Info'
title_varying_tesim: 'Variant Titles'
author_display_ssim: 'Author/Creator'
subject_tsim: 'Subjects'
edition_tsim: 'Edition'
publisher_details_display_ssim: 'Publisher'
pub_date_isi: 'Creation Date'
material_type_display_tesim: 'Format'
note_general_tsim: 'General Note'
language_tesim: 'Language'
summary_tesim: 'Summary'
isbn_ssim: 'Identifier'
publication_main_display_ssim: 'Publication Info'
format_ssim: 'Type'
lc_callnum_display_ssi: 'Call Number'
id: 'MMS ID'