title_display_tesim: 'Title'
title_addl_tesim: 'More Title Info'
title_varying_tesim: 'Variant Titles'
author_display_ssim: 'Author/Creator'
subject_tsim: 'Subjects'
edition_tsim: 'Edition'
published_ssm: 'Publisher'
pub_date_tesi: 'Creation Date'
material_type_display_tesim: 'Format'
note_general_tsim: 'General Note'
language_facet_tesim: 'Language'
summary_tesi: 'Summary'
isbn_ssim: 'Identifier'
publisher_location_ssm: 'Publication Info'
format_ssim: 'Type'
lc_callnum_display_ssi: 'Call Number'
id: 'MMS ID'