# frozen_string_literal: true
TEST_ITEM = {
  id: '123',
  author_display_ssim: ['George Jenkins'],
  author_ssim: ['George Jenkins', 'Someone Else'],
  format_ssim: ['Book'],
  isbn_ssim: ['SOME MAGICAL NUM .66G'],
  language_facet_tesim: ['English'],
  lc_callnum_display_ssi: 'ANOTHER MAGICAL NUM .78F',
  marc_resource_ssim: ['Electronic Resource'],
  pub_date_tesi: '2015',
  subject_era_ssim: ['1990-'],
  subject_geo_ssim: ['Texas'],
  subject_ssim: ['Frontier and pioneer life', 'Electronic books'],
  title_main_display_tesim: ['The Title of my Work'],
  title_details_display_tesim: ['The Title of my Work'],
  title_addl_tesim: ['More title info'],
  title_varying_tesim: ['Variant title'],
  subject_tsim: ['A sample subject'],
  edition_tsim: ['A sample edition'],
  title_series_ssim: ['American county histories'],
  publication_main_display_ssm: ['A dummy publication'],
  material_type_display_tesim: ['1 online resource (111 pages)'],
  note_general_tsim: ['General note'],
  publisher_details_display_ssm: ['Atlanta'],
  summary_tesim: ['Short summary'],
  genre_ssim: ['Genre example']
}.freeze
