# frozen_string_literal: true
TEST_ITEM = {
  id: '123',
  author_display_ssim: ['George Jenkins'],
  author_ssim: ['George Jenkins', 'Someone Else'],
  format_ssim: ['Book'],
  isbn_ssim: ['SOME MAGICAL NUM .66G'],
  language_tesim: ['English'],
  language_ssim: ['English'],
  lc_callnum_display_ssi: 'ANOTHER MAGICAL NUM .78F',
  marc_resource_ssim: ['Electronic Resource'],
  pub_date_isi: '2015',
  subject_era_ssim: ['1990-'],
  subject_geo_ssim: ['Texas'],
  subject_ssim: ['Frontier and pioneer life', 'Electronic books'],
  title_main_display_tesim: ['The Title of my Work'],
  title_details_display_tesim: ['The Title of my Work'],
  title_addl_tesim: ['More title info'],
  title_varying_tesim: ['Variant title'],
  subject_tsim: ['A sample subject'],
  edition_tsim: ['A sample edition'],
  collection_ssim: ['American county histories'],
  publication_main_display_ssim: ['A dummy publication'],
  material_type_display_tesim: ['1 online resource (111 pages)'],
  note_general_tsim: ['General note'],
  publisher_details_display_ssim: ['Atlanta'],
  summary_tesim: ['Short summary'],
  genre_ssim: ['Genre example'],
  lc_1letter_ssim: ['T - Technology'],
  library_ssim: ['UNIV'],
  title_series_ssim: ['The Jenkins Series'],
  title_added_entry_tesim: ['The Jenkins Story'],
  title_abbr_tesim: ['Jenk. Story'],
  title_translation_tesim: ['Le Stori de Jenkins'],
  author_addl_display_tesim: ['Tim Jenkins'],
  subject_display_ssim: ['Adventure--More Adventures.'],
  url_fulltext_ssm: ["{\"http://www.example2.com\":\"Link Text for Book\"}"],
  url_suppl_ssm: ['http://www.example.com'],
  issn_ssim: ['SOME OTHER MAGICAL NUMBER .12Q'],
  oclc_ssim: ['8675309'],
  other_standard_ids_ssim: ['M080142677'],
  publisher_number_ssim: ['H. 4260 H.'],
  author_vern_ssim: ['G. Jenkins'],
  title_vern_display_tesim: ['Title of my Work'],
  title_uniform_ssim: ['Uniform Title'],
  title_former_ssim: ['Former Titles'],
  title_later_ssim: ['Later Titles'],
  emory_collection_tesim: ["Emory's Collection"],
  finding_aid_url_ssim: ['http://www.example.com'],
  finding_aid_text_ssim: ['Finding Aid Text'],
  table_of_contents_tesim: ["1,2: Freddy's Coming For You"],
  note_publication_tesim: ['This is a Publication Note.'],
  note_publication_dates_tesim: ['Began with: Vol. 1, no. 1 (Jan./Feb. 2009)'],
  note_language_tesim: ['Language notes.'],
  note_accessibility_tesim: ['A note on accessibility'],
  note_technical_tesim: ['CDROM included.'],
  note_use_tesim: ['This eBook is made available Open Access under a CC BY-NC-ND 4.0 license:'],
  note_access_restriction_tesim: ['Open Access'],
  note_local_tesim: ['A local note.'],
  note_participant_tesim: ['A note about a performer.']
}.freeze
