# frozen_string_literal: true
require 'coveralls'
Coveralls.wear!

require 'webmock/rspec'
WebMock.disable_net_connect!(allow_localhost: true, allow: 'https://chromedriver.storage.googleapis.com')
RSpec::Matchers.define_negated_matcher :not_change, :change

# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

  config.before do
    stub_request(:get, "http://www.example.com/almaws/v1/bibs/9937241630902486/holdings?apikey=fakebibkey123")
      .to_return(status: 200, body: File.read(fixture_path + '/alma_request_holdings_test_file_1.xml'), headers: {})
    stub_request(:get, "http://www.example.com/almaws/v1/bibs/9937241630902486/request-options?user_id=mkadel&consider_dlr=false&apikey=fakebibkey123")
      .to_return(status: 200, body: File.read(fixture_path + '/alma_request_options_test_file_1.xml'), headers: {})
    stub_request(:get, "http://www.example.com/almaws/v1/bibs/990005988630302486?apikey=fakebibkey123&expand=p_avail,e_avail,d_avail&view=full")
      .to_return(status: 200, body: File.read(fixture_path + '/alma_availability_test_file.xml'), headers: {})
    stub_request(:get, "http://www.example.com/almaws/v1/bibs/990005059530302486?apikey=fakebibkey123&expand=p_avail,e_avail,d_avail&view=full")
      .to_return(status: 200, body: File.read(fixture_path + '/alma_availability_test_file_2.xml'), headers: {})
    stub_request(:get, "http://www.example.com/almaws/v1/bibs/123?apikey=fakebibkey123&expand=p_avail,e_avail,d_avail&view=full")
      .to_return(status: 200, body: File.read(fixture_path + '/alma_availability_test_file.xml'), headers: {})
    stub_request(:get, "http://www.example.com/almaws/v1/bibs/456?apikey=fakebibkey123&expand=p_avail,e_avail,d_avail&view=full")
      .to_return(status: 200, body: File.read(fixture_path + '/alma_availability_test_file_3.xml'), headers: {})
    stub_request(:get, "http://www.example.com/almaws/v1/bibs/789?apikey=fakebibkey123&expand=p_avail,e_avail,d_avail&view=full")
      .to_return(status: 200, body: File.read(fixture_path + '/alma_availability_test_file_4.xml'), headers: {})
    stub_request(
      :get,
      "https://smackety.alma.exlibrisgroup.com/view/oai/blah/request?verb=GetRecord&identifier=oai:alma.blah:single_record&metadataPrefix=marc21"
    ).to_return(status: 200, body: File.read(fixture_path + '/single_record.xml'), headers: {})
    stub_request(
      :get,
      "https://smackety.alma.exlibrisgroup.com/view/oai/blah/request?verb=GetRecord&identifier=oai:alma.blah:single_record_missing&metadataPrefix=marc21"
    ).to_return(status: 200, body: File.read(fixture_path + '/single_record_missing.xml'), headers: {})
    stub_request(
      :get,
      "https://smackety.alma.exlibrisgroup.com/view/oai/blah/request?verb=GetRecord&identifier=oai:alma.blah:single_record_updated&metadataPrefix=marc21"
    ).to_return(status: 200, body: File.read(fixture_path + '/single_record_updated.xml'), headers: {})
    stub_request(
      :get,
      "https://smackety.alma.exlibrisgroup.com/view/oai/blah/request?verb=GetRecord&identifier=oai:alma.blah:single_record_deleted&metadataPrefix=marc21"
    ).to_return(status: 200, body: File.read(fixture_path + '/single_record_deleted.xml'), headers: {})
    stub_request(
      :get,
      "https://smackety.alma.exlibrisgroup.com/view/oai/blah/request?metadataPrefix=marc21&set=blacklight4&until=2021-01-28T19:16:10Z&verb=ListRecords"
    ).to_return(status: 200, body: File.read(fixture_path + '/alma_small_set.xml'), headers: {})
    stub_request(
      :get,
      "https://smackety.alma.exlibrisgroup.com/view/oai/blah/request?metadataPrefix=marc21&set=blacklight_marc_resource&until=2021-01-28T19:16:10Z&verb=ListRecords"
    ).to_return(status: 200, body: File.read(fixture_path + '/alma_marc_resource.xml'), headers: {})
    stub_request(
      :get,
      "https://smackety.alma.exlibrisgroup.com/view/oai/blah/request?metadataPrefix=marc21&set=blacklight4&until=2021-02-15T19:16:10Z&verb=ListRecords"
    ).to_return(status: 200, body: File.read(fixture_path + '/alma_small_set_with_2_fields_missing.xml'), headers: {})
    stub_request(
      :get,
      "https://smackety.alma.exlibrisgroup.com/view/oai/blah/request?metadataPrefix=marc21&set=blacklight4&until=2021-01-29T19:16:10Z&verb=ListRecords"
    ).to_return(status: 200, body: File.read(fixture_path + '/alma_deleted_and_suppressed_records.xml'), headers: {})
    stub_request(
      :get,
      "https://smackety.alma.exlibrisgroup.com/view/oai/blah/request?metadataPrefix=marc21&set=blacklight4&until=2021-02-23T19:16:10Z&verb=ListRecords"
    ).to_return(status: 200, body: File.read(fixture_path + '/alma_small_set_with_1_new_1_updated_fields.xml'), headers: {})
    stub_request(
      :get,
      "https://jalapeno.alma.exlibrisgroup.com/view/oai/tabasco/request?identifier=oai:alma.blah:single_record&metadataPrefix=marc21&verb=GetRecord"
    ).to_return(status: 200, body: File.read(fixture_path + '/alma_availability_test_file.xml'), headers: {})
  end
end
